traefik:
  deployment:
    replicas: 1
  service:
    type: NodePort
    spec:
      externalTrafficPolicy: Cluster
    ports:
      web:
        nodePort: 32080
      websecure:
        nodePort: 32443
  # Enable HTTPS entrypoint and redirect HTTP -> HTTPS using new v34+ syntax
  ports:
    websecure:
      tls:
        enabled: true
  additionalArguments:
    - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  ingressRoute:
    dashboard:
      enabled: true
