---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCCB6fs+OuIgxWSKGgCPtbRHKunILoZJXq3ZpG1wf/Pe0TfnPjsJOxiiI4rcJHx3x4FLpqv2vZr31SjQFg+3HOHA7ajKLEUOAGFvSWWt14tkz86VGbMAdxdHSkRyIrpuBYZQITA2wgcnpyQHGo0MvLCV4FGYmbpimFL1ieyy9w+xVSuC3F48MUSjNpez3DPaHwUJw3OWNAcTmCPFZGFLPtXNoeQ/KBSdD8NApKOMst7h5t0gGHR75AvIq+P7XG1dRfBBqg1J/wSEey4vLGc3cHo2mFbaDdFGLBPL0oSMP2k13M2Dd2aIHBIji0jc6bWDMApjId3LpxG9tV/YAhtmlNBrJYSPDFxuHL/V0zoguRqk3vbLot57q1GDU+NWzyDLsXpVFzXuq2xboL8aRHj5KrB74o9yL1PWazXGszXc13zN2c7GdURkyWUvz9l654K12DBQvGzuT+ktSCjZ1dfZWDE6mTDljUqXZ/NPyfMEV52QqD9EvN7pWR4yfR3qFxdHBqFFbOe46uGMQA6NMR9OCmjfze6KY2yj2IcYWdxE9AYvNZwzqAavT8JANf1cIH43ItV+A3Lqy0EbhF4gnRg/B9urZURVSElZ7jD1K33Nn/Q2jnrurVHDOyOyX1BOEY4toep7VIFAg5S+xwmtk6JnulurGffB/0uQ7nwfWC7f3UbJAVMAvG9o+dbb/c5LNchWqZUfnFldWQMALDQFOcqQv1ghGAsXGxFt1DKc7oHUtZg9i9NpfCSRag8e53nvPdwXh0W3S0KUMh6D6adk7ugOGqhmfE7uBxpok/rrO6WhP84Y586mLfu5r01Ac2PkvvKN57/4OxnmgeWz06DKcgOJ8JNPa3b0yB9ejppnWVj86pgnZJbWzcxrUILiIjtV9iloYK5vvggzcgNPsdBtJ6Q+r6R2FiJJVBl2tIjGeFJsAxVe6+7Hy0d8LYx
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-token
      namespace: cloudflared
    type: Opaque
