---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCgAZ8lSk0IpAGn19RAEovu9s5SWO1VmMpzFmnNSmOygyVMy0NnzZa2TB4yWzSm0yrDor5kT6y6T15E22+VGZf/t4i/x6503tuPw7335lDNDg84Tv4uEgl9p1fe8+SxNnNeQOLdBqJ+5e5YWH8bMzlaAuCEQAN90yy7ug/yP5Im5Hz9ZKfpmTseHQUY4OskD4913zrbjM/RBRSWbmE5qnTqvFtQpI+44meHQ2fAnY9eunUzzIUZSHDsHjN/Tiq0ST5co3xujzr2vssUgXLGFNK7et424y3CDs5gTWYUuAMwcWcxmTXjZm7ciy9PFDC9jXqsYK2O8rODhB0JAFfN46gEQkj5lmjtskq/6/mBbNQzZjYGtcTd5AFywaqAhzGqheTIPF+pPWjFwfRYaMDTGy6bini+s8A4Dma1zwm2A+6uOYo/PCimXtV56IrrTxjRnIGS1wcZ208bS8F3GkYBkHgo3z7xGc3a4Or9yEeyTxTsD0WG7LE169iw2ko3XLGWeYJ1tdcL/I5Ok1z89WUIzvu02MkMdmF5KTEczilthxglq6XSef45WKFtyJXELIK+Zx2Uz6tWwKV/XBS/bR30ql3sU3bppRa7YOVlelEiLemEl0bi/xcX+Lkq/J59E8CWpHtSFEY9/RktuKZkncq5Ez/42AF+ywk7qOKdavS/tS30/QaTAvCbLq8sPi9QHjRQrSMWGdX9Kk8eMirGV32CdPdY5f0S0YBlCVV4BQHD7xZPK9/FHdiDversz8j19FqhDtRgmhpy/KyGV9U48KtPTZbaH00ynFr7eSLxMZ5GJ/hsM1zuVApWgwScEfFBhgiBfTtFxm/vOE1r+sN7Su0c+6daI1RRYESY8dpnZ6xwREPdrXdriXOHcKJiSt3B7zgfstLeG02kel4wY9wHfTmGy4OedF0wLArdroA7iJ5rMPlt+Xxzahj0MIGO
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-token
      namespace: cloudflared
    type: Opaque
